# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoMetar < Formula
  desc "Command-line tool for fetching METAR aviation weather reports"
  homepage "https://github.com/mdaguerre/go-metar"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mdaguerre/go-metar/releases/download/v1.2.0/go-metar_1.2.0_darwin_amd64.tar.gz"
      sha256 "a306b06254697abe3af42b5885fb4a2dd0af33db286494ae8ffb453ceb08d6cd"

      def install
        bin.install "go-metar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mdaguerre/go-metar/releases/download/v1.2.0/go-metar_1.2.0_darwin_arm64.tar.gz"
      sha256 "e848654489e1679c1207d49894a71e38451237b4a272a44da8273303fb9b105b"

      def install
        bin.install "go-metar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdaguerre/go-metar/releases/download/v1.2.0/go-metar_1.2.0_linux_amd64.tar.gz"
      sha256 "7cead6a14e1c7f9971faa0f151f4a787868be34a5dcb13b1c5156659a2208459"
      def install
        bin.install "go-metar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdaguerre/go-metar/releases/download/v1.2.0/go-metar_1.2.0_linux_arm64.tar.gz"
      sha256 "ba420e531b330ea1c858d543abd1d6d9b27af3df902aa385fab4b95a1d17c8b2"
      def install
        bin.install "go-metar"
      end
    end
  end

  test do
    system "#{bin}/go-metar", "--help"
  end
end
