# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoMetar < Formula
  desc "Command-line tool for fetching METAR aviation weather reports"
  homepage "https://github.com/mdaguerre/go-metar"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mdaguerre/go-metar/releases/download/v1.3.0/go-metar_1.3.0_darwin_amd64.tar.gz"
      sha256 "142f439d3ded4290e48777964983d6361e4d492e783039003cf1d146bb5378b3"

      def install
        bin.install "go-metar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mdaguerre/go-metar/releases/download/v1.3.0/go-metar_1.3.0_darwin_arm64.tar.gz"
      sha256 "6554109c00a90f80edf69486bc2cde869d1bee031cdab3f622256c418f598fd6"

      def install
        bin.install "go-metar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdaguerre/go-metar/releases/download/v1.3.0/go-metar_1.3.0_linux_amd64.tar.gz"
      sha256 "e7bc9288516d82e521c7206f8405c524ab38d09e820049b38917b7584caa46a1"
      def install
        bin.install "go-metar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdaguerre/go-metar/releases/download/v1.3.0/go-metar_1.3.0_linux_arm64.tar.gz"
      sha256 "78b94e6388a5c59db85b936f78d0e713e636dde09ae5fdae54f3113ae0594d6c"
      def install
        bin.install "go-metar"
      end
    end
  end

  test do
    system "#{bin}/go-metar", "--help"
  end
end
