# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoMetar < Formula
  desc "Command-line tool for fetching METAR aviation weather reports"
  homepage "https://github.com/mdaguerre/go-metar"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mdaguerre/go-metar/releases/download/v1.0.0/go-metar_1.0.0_darwin_amd64.tar.gz"
      sha256 "768ffb07054087f75cc18043eb037d9352cd7d4a2c6abeb356ee0b4b444316ec"

      def install
        bin.install "go-metar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mdaguerre/go-metar/releases/download/v1.0.0/go-metar_1.0.0_darwin_arm64.tar.gz"
      sha256 "c1795bcd7b33b5e28248750e87bb39d4b2c020daec55e5b56ce462d0eca26c6f"

      def install
        bin.install "go-metar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdaguerre/go-metar/releases/download/v1.0.0/go-metar_1.0.0_linux_amd64.tar.gz"
      sha256 "050f88a61935483231309a21bd548e0bb4b3c304aad2240adfac73a752f1f415"
      def install
        bin.install "go-metar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdaguerre/go-metar/releases/download/v1.0.0/go-metar_1.0.0_linux_arm64.tar.gz"
      sha256 "0367bd2c8968812ca69efa904c401344782a7850d7126faf533157c8d09af9e5"
      def install
        bin.install "go-metar"
      end
    end
  end

  test do
    system "#{bin}/go-metar", "--help"
  end
end
